_BASE_: "../../configs/Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "../../pretrain_models/R-50-condconv-8.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    COND_CONV_ON_PER_STAGE: [True, True, True, True]
    HARD_GENERATE:
      IN_CHANNELS: 16
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0025
DATASETS:
  TRAIN: ("routine_train",)
  TEST: ("routine_test",)
OUTPUT_DIR: "logs"