_BASE_: "../../configs/Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "../../pretrain_models/mobilenet_v2-b0353104.pth"
  MASK_ON: False
  RESNETS:
    OUT_FEATURES: ["res4"]
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
DATASETS:
  TRAIN: ("domain_train",)
  TEST: ("domain_test",)
OUTPUT_DIR: "logs"