_BASE_: "../../configs/Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "../../pretrain_models/R-18.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  VFS:
    SAMPLE_RANGE: 5
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
DATASETS:
  TRAIN: ("domain_train",)
  TEST: ("domain_test",)
DATALOADER:
  NUM_WORKERS: 4
  SAMPLER_TRAIN: VFSPairSampler
OUTPUT_DIR: "logs"