_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  WARMUP_ITERS: 5000
DATASETS:
  TRAIN: ("domain_train",)
  TEST: ("domain_test",)
