_BASE_: "../../configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "../../pretrain_models/R-50-condconv-32.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    COND_CONV_ON_PER_STAGE: [False, False, False, True]
    COND_CONV_NUM_EXPERTS: 32
    COND_CONV_DROPOUT_RATE: 0.
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
DATASETS:
  TRAIN: ("domain_train",)
  TEST: ("domain_test",)
OUTPUT_DIR: "logs"
